name: "Legislation Tools Pipeline"
description: "Clones repositories and runs the legislation tools pipeline on cloned data"
author: "Your Name"

inputs:
  sources:
    description: "List of repositories to clone (space-separated source names)"
    required: true
  token:
    description: "GitHub token for authentication"
    required: false
  output_dir:
    description: "Output directory for cloned repositories"
    required: false
    default: "logs/windy-civi-pipelines"
  sort:
    description: "Sort order for results (ASC or DESC)"
    required: false
    default: "DESC"
  limit:
    description: "Limit the number of results (positive integer)"
    required: false
  output_file:
    description: "Path to the output file"
    required: false
    default: "./logs/windy-civi-pipelines.log"

outputs:
  directories:
    description: "Comma-separated list of cloned directory paths"
    value: ${{ steps.pipeline.outputs.directories }}
  repository-count:
    description: "Number of repositories cloned"
    value: ${{ steps.pipeline.outputs.repository-count }}

runs:
  using: "composite"
  steps:
    - name: Run pipeline
      id: pipeline
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
        GITHUB_OUTPUT: ${{ github.output }}
      run: |
        SCRIPT="${{ github.action_path }}/main.sh"
        chmod +x "$SCRIPT"
        
        # Build command with flags
        CMD="$SCRIPT"
        
        # Add --output-dir flag (has default in action.yml)
        CMD="$CMD --output-dir=${{ inputs.output_dir }}"
        
        # Add --sort flag (has default in action.yml)
        CMD="$CMD --sort=${{ inputs.sort }}"
        
        # Add --limit flag only if provided (no default)
        if [ -n "${{ inputs.limit }}" ]; then
          CMD="$CMD --limit=${{ inputs.limit }}"
        fi
        
        # Add --output flag (has default in action.yml)
        CMD="$CMD --output=${{ inputs.output_file }}"
        
        # Add sources as positional arguments
        # Split sources by space and add each as an argument
        for source in ${{ inputs.sources }}; do
          CMD="$CMD $source"
        done
        
        # Execute the command
        $CMD
