name: "Govbot RSS Publisher"
description: "Generate and publish RSS feeds from govbot.yml configuration"
branding:
  icon: 'rss'
  color: 'orange'

inputs:
  tags:
    description: 'Comma-separated list of tags to include in feed (default: all tags from govbot.yml)'
    required: false
  limit:
    description: 'Limit number of entries per feed'
    required: false
  output-dir:
    description: 'Output directory for RSS feed (default: from govbot.yml publish.output_dir)'
    required: false
  output-file:
    description: 'Output filename for RSS feed (default: from govbot.yml publish.output_file)'
    required: false
  govbot-dir:
    description: 'Govbot directory (default: $CWD/.govbot/repos, or GOVBOT_DIR env var)'
    required: false

outputs:
  feed-path:
    description: 'Path to the generated RSS feed file'
    value: ${{ steps.publish.outputs.feed-path }}

runs:
  using: "composite"
  steps:
    - name: Download govbot binary
      shell: bash
      run: |
        mkdir -p "${{ github.action_path }}/bin"
        curl -fsSL "https://github.com/windy-civi/toolkit/releases/download/nightly/govbot-linux-x86_64" \
          -o "${{ github.action_path }}/bin/govbot"
        chmod +x "${{ github.action_path }}/bin/govbot"
    
    - name: Clone legislation repositories
      id: clone
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        # Set GOVBOT_DIR
        if [ -n "${{ inputs.govbot-dir }}" ]; then
          export GOVBOT_DIR="${{ inputs.govbot-dir }}"
        else
          export GOVBOT_DIR="${{ github.workspace }}/.govbot"
        fi
        
        # Check if govbot.yml exists
        if [ ! -f "${{ github.workspace }}/govbot.yml" ]; then
          echo "::error::govbot.yml not found in repository root"
          exit 1
        fi
        
        # Read repos from govbot.yml (simple parsing - assumes YAML format)
        # For now, we'll clone all repos by default
        # Users can specify repos in govbot.yml
        echo "📥 Cloning legislation repositories..."
        ${{ github.action_path }}/bin/govbot clone all \
          --govbot-dir "$GOVBOT_DIR" || true
    
    - name: Generate RSS feed
      id: publish
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        # Set GOVBOT_DIR
        if [ -n "${{ inputs.govbot-dir }}" ]; then
          export GOVBOT_DIR="${{ inputs.govbot-dir }}"
        else
          export GOVBOT_DIR="${{ github.workspace }}/.govbot"
        fi
        # Build command arguments
        ARGS=""
        
        # Add tags if specified
        if [ -n "${{ inputs.tags }}" ]; then
          # Convert comma-separated to space-separated
          TAGS=$(echo "${{ inputs.tags }}" | tr ',' ' ')
          ARGS="$ARGS --tags $TAGS"
        fi
        
        # Add limit if specified
        if [ -n "${{ inputs.limit }}" ]; then
          ARGS="$ARGS --limit ${{ inputs.limit }}"
        fi
        
        # Add output directory if specified
        if [ -n "${{ inputs.output-dir }}" ]; then
          ARGS="$ARGS --output-dir ${{ inputs.output-dir }}"
        fi
        
        # Add output file if specified
        if [ -n "${{ inputs.output-file }}" ]; then
          ARGS="$ARGS --output-file ${{ inputs.output-file }}"
        fi
        
        # Add govbot-dir if specified
        if [ -n "${{ inputs.govbot-dir }}" ]; then
          ARGS="$ARGS --govbot-dir ${{ inputs.govbot-dir }}"
        fi
        
        # Run publish command
        # govbot.yml is automatically found in workspace root
        ${{ github.action_path }}/bin/govbot publish $ARGS
        
        # Determine output path (read from govbot.yml or use defaults)
        if [ -n "${{ inputs.output-dir }}" ]; then
          OUTPUT_DIR="${{ inputs.output-dir }}"
        else
          # Try to read from govbot.yml, default to feeds
          OUTPUT_DIR=$(grep -A 5 "^publish:" "${{ github.workspace }}/govbot.yml" | grep "output_dir:" | awk '{print $2}' | tr -d '"' || echo "feeds")
        fi
        
        if [ -n "${{ inputs.output-file }}" ]; then
          OUTPUT_FILE="${{ inputs.output-file }}"
        else
          # Try to read from govbot.yml, default to feed.xml
          OUTPUT_FILE=$(grep -A 5 "^publish:" "${{ github.workspace }}/govbot.yml" | grep "output_file:" | awk '{print $2}' | tr -d '"' || echo "feed.xml")
        fi
        
        echo "feed-path=${{ github.workspace }}/$OUTPUT_DIR/$OUTPUT_FILE" >> $GITHUB_OUTPUT
