name: "Govbot"
description: "Tag bills, push tags, and publish RSS feeds from govbot.yml configuration"
branding:
  icon: 'rss'
  color: 'orange'

inputs:
  tags:
    description: 'Comma-separated list of tags to include in feed (default: all tags from govbot.yml)'
    required: false
  limit:
    description: 'Limit number of entries per feed'
    required: false
  output-dir:
    description: 'Output directory for RSS feed (default: from govbot.yml publish.output_dir)'
    required: false
  output-file:
    description: 'Output filename for RSS feed (default: from govbot.yml publish.output_file)'
    required: false
  govbot-dir:
    description: 'Govbot directory (default: $CWD/.govbot/repos, or GOVBOT_DIR env var)'
    required: false
  push-tags:
    description: 'Whether to commit and push tag files (default: true)'
    required: false
    default: 'true'
  deploy-pages:
    description: 'Whether to deploy RSS feeds to GitHub Pages (default: true)'
    required: false
    default: 'true'

outputs:
  feed-path:
    description: 'Path to the generated RSS feed file'
    value: ${{ steps.publish.outputs.feed-path }}
  feed-dir:
    description: 'Directory containing the generated RSS feed'
    value: ${{ steps.publish.outputs.feed-dir }}

runs:
  using: "composite"
  steps:
    - name: Download govbot binary
      shell: bash
      run: |
        mkdir -p "${{ github.action_path }}/bin"
        curl -fsSL "https://github.com/windy-civi/toolkit/releases/download/nightly/govbot-linux-x86_64" \
          -o "${{ github.action_path }}/bin/govbot"
        chmod +x "${{ github.action_path }}/bin/govbot"
    
    - name: Set GOVBOT_DIR
      id: set-govbot-dir
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        if [ -n "${{ inputs.govbot-dir }}" ]; then
          export GOVBOT_DIR="${{ inputs.govbot-dir }}"
        else
          export GOVBOT_DIR="${{ github.workspace }}/.govbot"
        fi
        echo "GOVBOT_DIR=$GOVBOT_DIR" >> $GITHUB_ENV
        echo "repos-dir=$GOVBOT_DIR/repos" >> $GITHUB_OUTPUT
    
    - name: Restore repos cache
      id: cache-repos
      uses: actions/cache@v4
      with:
        path: ${{ steps.set-govbot-dir.outputs.repos-dir }}
        key: govbot-repos-${{ runner.os }}-${{ hashFiles('govbot.yml') }}
        restore-keys: |
          govbot-repos-${{ runner.os }}-
    
    - name: Clone legislation repositories
      id: clone
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        # Check if govbot.yml exists
        if [ ! -f "${{ github.workspace }}/govbot.yml" ]; then
          echo "::error::govbot.yml not found in repository root"
          exit 1
        fi
        
        # Read repos from govbot.yml (simple parsing - assumes YAML format)
        # For now, we'll clone all repos by default
        # Users can specify repos in govbot.yml
        echo "ðŸ“¥ Cloning legislation repositories..."
        ${{ github.action_path }}/bin/govbot clone all \
          --govbot-dir "$GOVBOT_DIR" || true
    
    - name: Save repos cache
      if: steps.cache-repos.outputs.cache-hit != 'true'
      uses: actions/cache@v4
      with:
        path: ${{ steps.set-govbot-dir.outputs.repos-dir }}
        key: govbot-repos-${{ runner.os }}-${{ hashFiles('govbot.yml') }}
    
    - name: Tag bills
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        echo "ðŸ·ï¸  Tagging bills..."
        ${{ github.action_path }}/bin/govbot logs | ${{ github.action_path }}/bin/govbot tag || true
    
    - name: Commit and push tag files
      if: inputs.push-tags == 'true'
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        git status

        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
        # Add all .tag.json files
        git add --all :/ || true
        
        # Check if there are changes to commit
        if git diff --cached --quiet; then
          echo "No tag file changes to commit"
        else
          git commit -m "Update tag files from govbot tag" || true
          git push || true
        fi
    
    - name: Generate RSS feed
      id: publish
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        # Build command arguments
        ARGS=""
        
        # Add tags if specified
        if [ -n "${{ inputs.tags }}" ]; then
          # Convert comma-separated to space-separated
          TAGS=$(echo "${{ inputs.tags }}" | tr ',' ' ')
          ARGS="$ARGS --tags $TAGS"
        fi
        
        # Add limit if specified
        if [ -n "${{ inputs.limit }}" ]; then
          ARGS="$ARGS --limit ${{ inputs.limit }}"
        fi
        
        # Add output directory if specified
        if [ -n "${{ inputs.output-dir }}" ]; then
          ARGS="$ARGS --output-dir ${{ inputs.output-dir }}"
        fi
        
        # Add output file if specified
        if [ -n "${{ inputs.output-file }}" ]; then
          ARGS="$ARGS --output-file ${{ inputs.output-file }}"
        fi
        
        # Add govbot-dir if specified
        if [ -n "${{ inputs.govbot-dir }}" ]; then
          ARGS="$ARGS --govbot-dir ${{ inputs.govbot-dir }}"
        fi
        
        # Run publish command
        # govbot.yml is automatically found in workspace root
        ${{ github.action_path }}/bin/govbot publish $ARGS
        
        # Determine output path (read from govbot.yml or use defaults)
        if [ -n "${{ inputs.output-dir }}" ]; then
          OUTPUT_DIR="${{ inputs.output-dir }}"
        else
          # Try to read from govbot.yml, default to feeds
          OUTPUT_DIR=$(grep -A 5 "^publish:" "${{ github.workspace }}/govbot.yml" | grep "output_dir:" | awk '{print $2}' | tr -d '"' || echo "feeds")
        fi
        
        if [ -n "${{ inputs.output-file }}" ]; then
          OUTPUT_FILE="${{ inputs.output-file }}"
        else
          # Try to read from govbot.yml, default to feed.xml
          OUTPUT_FILE=$(grep -A 5 "^publish:" "${{ github.workspace }}/govbot.yml" | grep "output_file:" | awk '{print $2}' | tr -d '"' || echo "feed.xml")
        fi
        
        echo "feed-path=${{ github.workspace }}/$OUTPUT_DIR/$OUTPUT_FILE" >> $GITHUB_OUTPUT
        echo "feed-dir=${{ github.workspace }}/$OUTPUT_DIR" >> $GITHUB_OUTPUT
    
    - name: Setup Pages
      if: inputs.deploy-pages == 'true'
      uses: actions/configure-pages@v4
      with:
        enablement: true
    
    - name: Upload artifact
      if: inputs.deploy-pages == 'true'
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ steps.publish.outputs.feed-dir }}
    
    - name: Deploy to GitHub Pages
      if: inputs.deploy-pages == 'true'
      id: deployment
      uses: actions/deploy-pages@v4
